config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :invoices
  resources :clients do
    resources :invoices
  end
  resources :companies do
    resources :invoices
  end

  root to: "companies#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :company, inverse_of: :invoices
  belongs_to :client, inverse_of: :invoices
  has_many :invoice_items, inverse_of: :invoice, dependent: :destroy

  accepts_nested_attributes_for :invoice_items, reject_if: :all_blank, allow_destroy: true

  validates :invoice_no, presence: true, numericality: true, uniqueness: {scope: [:company, :client]}
  validates :invoice_date, :date_of_supply, :company, :client, presence: true

  before_validation :populate_invoice_number, on: :create
  before_validation :populate_invoice_date, on: :create


  def total_amount
    invoice_items.collect{|inv| inv.amount}.sum
  end

  def total_tax
    invoice_items.collect{|inv| inv.gst_tax}.sum
  end

  def total_amount_with_tax
    total_amount + total_tax*(is_interstate? ? 1 : 2)
  end

  def delete
    raise TryToDeleteNonDeletableEntity
  end

  def destroy
    raise TryToDeleteNonDeletableEntity
  end

  def is_interstate?
    company.code != client.code
  end

  private

  def populate_invoice_number
    self.invoice_no = (self.company.invoices.order('invoice_no desc').take.invoice_no rescue 0) + 1
  end

  def populate_invoice_date
    return unless invoice_date.nil?
    self.invoice_date = Date.today()
  end


end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Hash[(
                     if params[:client_id].present?
                       Client.find(params[:client_id]).invoices.includes([:company, :client])
                     elsif params[:company_id].present?
                       Company.find(params[:company_id]).invoices.includes([:company, :client])
                     else
                       Invoice.includes([:company, :client]).all
                     end).group_by { |i| i.invoice_date.beginning_of_month }.sort_by { |k, v| k.to_time }.reverse]
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @invoice.invoice_items.build
  end

  # GET /invoices/1/edit
  def edit
    @invoice.invoice_items.build if @invoice.invoice_items.empty?
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def invoice_params
    params.require(:invoice).permit(:company_id, :client_id, :invoice_no, :invoice_date, :reverse_charge, :transport_mode,
                                    :vehicle_no, :date_of_supply, :place_for_supply,
                                    invoice_items_attributes: [:id, :invoice_id, :description, :hsn_code, :udm, :quantity,
                                                               :rate, :amount, :gst_rate, :discount, :_destroy])
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
    <% if invoice.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice_item from being saved:</h2>

          <ul>
            <% invoice.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row">
      <div class="col-md-6 mb-3">
        <%= form.label :company_id, 'Company' %>
        <%= form.select :company_id, Company.all.collect { |company| [company.name, company.id] }, {prompt: 'Select Company'}, class: "form-control #{validation_class(invoice, :company_id)}", id: :invoice_company_id %>
        <% if (error_message_present_for?(invoice, :company_id)) %>
            <div class="invalid-feedback">
              <%== error_messages(invoice, :company_id) %>
            </div>
        <% end %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :client_id, 'Client' %>
        <%= form.select :client_id, Client.all.collect { |client| [client.name, client.id] }, {prompt: 'Select Client'}, class: "form-control #{validation_class(invoice, :client_id)}", id: :invoice_client_id %>
        <% if (error_message_present_for?(invoice, :client_id)) %>
            <div class="invalid-feedback">
              <%== error_messages(invoice, :client_id) %>
            </div>
        <% end %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :invoice_date %>
        <div class="form-group row" style="margin-bottom: 0;">
          <div class="col-md-12 mb-3">
            <%= form.date_select :invoice_date, {}, style: "display: inline-block; max-width:32.5%", class: "col-md-4  form-control #{validation_class(invoice, :invoice_date)}", id: :invoice_invoice_date %>
            <% if (error_message_present_for?(invoice, :invoice_date)) %>
                <div class="invalid-feedback">
                  <%== error_messages(invoice, :invoice_date) %>
                </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :date_of_supply %>
        <%= form.text_field :date_of_supply, class: "form-control", id: :invoice_date_of_supply %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :place_for_supply %>
        <%= form.text_field :place_for_supply, class: "form-control", id: :invoice_place_for_supply %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :reverse_charge, 'Reverse charge (Y/N)' %>
        <%= form.text_field :reverse_charge, class: "form-control", id: :invoice_reverse_charge %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :transport_mode %>
        <%= form.text_field :transport_mode, class: "form-control", id: :invoice_transport_mode %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :vehicle_no %>
        <%= form.text_field :vehicle_no, class: "form-control", id: :invoice_vehicle_no %>
      </div>
    </div>
    <div class="row row-bordered">
      <div class="col-md-10 mb-3">
        <h2>Invoice items</h2>
      </div>
      <div class="col-md-2 mb-3">
        <a href="javascript:void(0)", rel='add_invoice_item' class='btn btn-primary'>Add invoice item</a>
      </div>
    </div>
    <%= form.fields_for :invoice_items do |invoice_item| %>
        <div class="row" rel="invoice_item">

          <div class="col-md-4 mb-2">
            <%= invoice_item.label :description %>
            <%= invoice_item.text_field :description, class: "form-control" %>
          </div>

          <div class="col-md-1 mb-1">
            <%= invoice_item.label :quantity %>
            <%= invoice_item.text_field :quantity, class: "form-control" %>
          </div>

          <div class="col-md-2 mb-1">
            <%= invoice_item.label :rate %>
            <%= invoice_item.text_field :rate, class: "form-control" %>
          </div>

          <div class="col-md-1 mb-1">
            <%= invoice_item.label :gst_rate %>
            <%= invoice_item.text_field :gst_rate, class: "form-control" %>
          </div>

          <div class="col-md-1 mb-1">
            <%= invoice_item.label :discount %>
            <%= invoice_item.text_field :discount, class: "form-control" %>
          </div>

          <div class="col-md-1 mb-1">
            <%= invoice_item.label :hsncode %>
            <%= invoice_item.text_field :hsn_code, class: "form-control" %>
          </div>

          <div class="col-md-1 mb-1">
            <%= invoice_item.label :udm %>
            <%= invoice_item.text_field :udm, class: "form-control" %>
          </div>
          <div class="col-md-1 mb-1">
            <div style="display: table;min-height: 100%">
              <div style="display: table-row">
              <div style="display: table-cell;" class="align-middle">
              <a href='javascript:void(0)' rel="deleteInvoice" style='color:red;' title="Delete the invoice item"><%= fa_icon "close" %></a></div>
              </div>
            </div>

          </div>
        </div>
    <% end %>
    <%= form.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/invoices/_interstate_bottom_section.html.erb
<div class="row item-gap" >
  <div class="col-md-6 col-sm-6 text-uppercase both_border text-center fill border-right">
    total
  </div>
  <div class="col-md-2 col-sm-2 both_border border-right">
    <%= @invoice.total_amount %>
  </div>
  <div class="col-md-1 col-sm-1 both_border border-right">

  </div>
  <div class="col-md-1 col-sm-1 both_border border-right">
    <%= @invoice.total_tax %>
  </div>
  <div class="col-md-2 col-sm-2 both_border">
    <%= @invoice.total_amount_with_tax %>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-sm-6 border-right">
    <div class='row'>
      <div class="col-md-12 col-sm-12 text-capitalize text-center fill  border_bottom">total invoice amount in words
      </div>
      <div class="col-md-12 col-sm-12"><%= number_to_currency_in_words(@invoice.total_amount_with_tax, currency: :rupee) %></div>
    </div>
  </div>
  <div class="col-md-6 col-sm-6">
    <div class='row text-capitalize'>
      <div class="col-md-8 col-sm-8 border-right border_bottom">total amount before tax</div>
      <div class="col-md-4 col-sm-4 border_bottom"><%= @invoice.total_amount %></div>

      <div class="col-md-8 col-sm-8 border-right border_bottom">GST</div>
      <div class="col-md-4 col-sm-4 border_bottom"><%= @invoice.total_tax %></div>

      <div class="col-md-8 col-sm-8 border-right border_bottom">total amount after tax</div>
      <div class="col-md-4 col-sm-4 border_bottom">
        <strong><%= @invoice.total_amount_with_tax %></strong></div>

      <div class="col-md-8 col-sm-8 border-right border_bottom">GST on reverse charges</div>
      <div class="col-md-4 col-sm-4 border_bottom">0</div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-sm-6 border-right">
    <div class='row text-uppercase'>
      <div class="col-md-12 col-sm-12 text-center fill both_border">Bank Details</div>
      <div class="col-md-3 col-sm-3 border-right border_bottom"> Bank ac</div>
      <div class="col-md-9 col-sm-9 border_bottom"><%= @invoice.company.account_no %> </div>

      <div class="col-md-3 col-sm-3 border-right border_bottom"> ifsc code</div>
      <div class="col-md-9 col-sm-9 border_bottom"><%= @invoice.company.ifsc_code %> </div>

      <div class="col-md-12 col-sm-12"> Terms and conditions</div>
    </div>
  </div>
  <div class="col-md-6 col-sm-6">
    <div class='row'>
      <div class="col-md-12 col-sm-12">Certified that the particulars given above are true and correct</div>
      <div class="col-md-12 col-sm-12 text-uppercase text-center signature">
        <strong> <%= @invoice.company.name %></strong></div>
      <div class="col-md-12 col-sm-12 text-center big-gap">
        <strong>Authorised signatory</strong>
      </div>
    </div>
  </div>
</div>

app/views/invoices/_intrastate_bottom_section.html.erb
<div class="row item-gap">
  <div class="col-md-6 col-sm-6 text-uppercase both_border text-center fill border-right">
    total
  </div>
  <div class="col-md-1 col-sm-1 both_border border-right">
    <%= @invoice.total_amount %>
  </div>
  <div class="col-md-1 col-sm-1 both_border border-right">

  </div>
  <div class="col-md-1 col-sm-1 both_border border-right">
    <%= @invoice.total_tax %>
  </div>
  <div class="col-md-1 col-sm-1 both_border border-right">

  </div>
  <div class="col-md-1 col-sm-1 both_border border-right">
    <%= @invoice.total_tax %>
  </div>
  <div class="col-md-1 col-sm-1 both_border">
    <%= @invoice.total_amount_with_tax %>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-sm-6 border-right">
    <div class='row'>
      <div class="col-md-12 col-sm-12 text-capitalize text-center fill  border_bottom">total invoice amount in words
      </div>
      <div class="col-md-12 col-sm-12"><%= number_to_currency_in_words(@invoice.total_amount_with_tax, currency: :rupee) %></div>
    </div>
  </div>
  <div class="col-md-6 col-sm-6">
    <div class='row text-capitalize'>
      <div class="col-md-10 col-sm-10 border-right border_bottom">total amount before tax</div>
      <div class="col-md-2 col-sm-2 border_bottom"><%= @invoice.total_amount %></div>

      <div class="col-md-10 col-sm-10 border-right border_bottom">CGST</div>
      <div class="col-md-2 col-sm-2 border_bottom"><%= @invoice.total_tax %></div>

      <div class="col-md-10 col-sm-10 border-right border_bottom">SGST</div>
      <div class="col-md-2 col-sm-2 border_bottom"><%= @invoice.total_tax %></div>

      <div class="col-md-10 col-sm-10 border-right border_bottom">total amount after tax</div>
      <div class="col-md-2 col-sm-2 border_bottom">
        <strong><%= @invoice.total_amount_with_tax %></strong></div>

      <div class="col-md-10 col-sm-10 border-right border_bottom">GST on reverse charges</div>
      <div class="col-md-2 col-sm-2 border_bottom">0</div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6 col-sm-6 border-right">
    <div class='row text-uppercase'>
      <div class="col-md-12 col-sm-12 text-center fill both_border">Bank Details</div>
      <div class="col-md-3 col-sm-3 border-right border_bottom"> Bank ac</div>
      <div class="col-md-9 col-sm-9 border_bottom"><%= @invoice.company.account_no %> </div>

      <div class="col-md-3 col-sm-3 border-right border_bottom"> ifsc code</div>
      <div class="col-md-9 col-sm-9 border_bottom"><%= @invoice.company.ifsc_code %> </div>

      <div class="col-md-12 col-sm-12"> Terms and conditions</div>
    </div>
  </div>
  <div class="col-md-6 col-sm-6">
    <div class='row'>
      <div class="col-md-12 col-sm-12">Certified that the particulars given above are true and correct</div>
      <div class="col-md-12 col-sm-12 text-uppercase text-center signature">
        <strong> <%= @invoice.company.name %></strong></div>
      <div class="col-md-12 col-sm-12 text-center big-gap">
        <strong>Authorised signatory</strong>
      </div>
    </div>
  </div>
</div>

app/views/invoices/edit.html.erb
<div class="container mt-5">
  <section>
    <h1>Editing Invoice</h1>
  </section>

  <%= render 'form', invoice: @invoice %>

  <%= link_to 'Show', @invoice %> |
  <%= link_to 'Back', invoices_path %>
</div>

app/views/invoices/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Invoices</h1>

    <p class="lead text-muted">List of all Invoices generated under PRABHAT GROUP</p>

    <p>
      <%= link_to "Generate Invoice", new_invoice_path, class: 'btn btn-primary' %>
    </p>
  </div>
</section>

<div class="album">
  <div class="container">


    <% @invoices.each do |month, invoices| %>
        <div class="row row-bordered">
          <h5><%= pluralize(invoices.count, 'Invoice') %> for <%= month.strftime('%B, %Y') %> </h5>
        </div>
        <div class="row">
          <table class="table table-hover">
            <thead>
            <tr>
              <th>Invoice no</th>
              <th>Company</th>
              <th>Client</th>
              <th>Invoice date</th>
              <th>Invoice Amount</th>
              <th colspan="3"></th>
            </tr>
            </thead>

            <tbody>
            <% invoices.each do |invoice| %>
                <tr>
                  <th scope="row"><%= invoice.invoice_no %></th>
                  <td><%= invoice.company.name %></td>
                  <td><%= invoice.client.name %></td>
                  <td><%= invoice.invoice_date %></td>
                  <td><%= invoice.total_amount %></td>
                  <td><%= link_to 'Show', invoice %></td>
                  <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
                  <td><%= link_to 'Destroy', invoice, method: :delete, data: {confirm: 'Are you sure?'} %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
    <% end %>

  </div>
</div>

app/views/invoices/new.html.erb
<div class="container mt-5">
  <section>
    <h1>Generate Invoice</h1>
  </section>
  <%= render 'form', invoice: @invoice %>

  <%= link_to 'Back', invoices_path %>
</div>

app/views/invoices/show.html.erb
<div class="container ">
  <div class="page-break"></div>
  <% ['Original for Recipient', 'Duplicate for Service Provider'].each do |bill_for| %>
      <div class="row mt-5 invoice_show section-to-print">
        <div class="col-lg-12 col-sm-12">
          <div class="row">
            <div class="col-lg-8 col-sm-8 ml-auto text-center">
              <h2 class="text-uppercase mb-0 mt-1"><strong><%= @invoice.company.name %></strong></h2>
              <h5 class="text-uppercase mb-0"><%= @invoice.company.address %></h5>
              <h5 class="text-uppercase mb-0"><%= @invoice.company.contact %></h5>
            </div>
            <div class="col-lg-2  col-sm-2 align-self-end text-center">
              <%= bill_for %>
            </div>
          </div>
          <div class="row mt-5 border_bottom_complete">
            <div class="col-lg-12 col-sm-12 text-center">
              <strong class="text-uppercase">GSTIN: <%= @invoice.company.gstno %></strong>
            </div>
          </div>

          <div class="row mt-1 both_border fill">
            <div class="col-lg-12 col-sm-12 text-center">
              <strong class="text-uppercase">tax invoice</strong>
            </div>
          </div>

          <div class="row text-uppercase">
            <div class="col-lg-6 col-sm-6">
              <div class="row border-right border_bottom">
                <div class="col-lg-9 col-sm-6 border_bottom">
                  invoice no :
                </div>
                <div class="col-lg-3 col-sm-6 border_bottom">
                  <%= @invoice.invoice_no %>
                </div>
                <div class="col-lg-9 col-sm-6 border_bottom">
                  INVOICE Date :
                </div>
                <div class="col-lg-3 col-sm-6 border_bottom">
                  <%= @invoice.invoice_date.strftime('%d-%m-%Y') %>
                </div>
                <div class="col-lg-9 col-sm-6 border_bottom">
                  Reverse charge (Y/N) :
                </div>
                <div class="col-lg-3 col-sm-6 border_bottom">
                  <%= @invoice.reverse_charge %>
                </div>

                <div class="col-lg-3 col-sm-5">
                  STATE :
                </div>
                <div class="col-lg-5 col-sm-3 border-right">
                  <%= @invoice.company.state %>
                </div>
                <div class="col-lg-2 col-sm-3">
                  CODE :
                </div>
                <div class="col-lg-2 col-sm-1">
                  <%= @invoice.company.code %>
                </div>
              </div>
            </div>
            <div class="col-lg-6 col-sm-6">
              <div class="row">
                <div class="col-lg-7 col-sm-6 border_bottom">
                  Transport mode :
                </div>
                <div class="col-lg-5 col-sm-6 border_bottom">
                  <%= @invoice.transport_mode %>
                </div>
                <div class="col-lg-7 col-sm-6 border_bottom">
                  vehicle number :
                </div>
                <div class="col-lg-5 col-sm-6 border_bottom">
                  <%= @invoice.vehicle_no %>
                </div>
                <div class="col-lg-7 col-sm-6 border_bottom">
                  Date of supply :
                </div>
                <div class="col-lg-5 col-sm-6 border_bottom">
                  <%= @invoice.date_of_supply %>
                </div>
                <div class="col-lg-7 col-sm-6 border_bottom">
                  Place of supply :
                </div>
                <div class="col-lg-5 col-sm-6 border_bottom">
                  <%= @invoice.place_for_supply %>
                </div>
              </div>
            </div>
          </div>

          <div class="row text-uppercase mt-3">
            <% ['Bill to Party', 'Ship to Party'].each_with_index do |section, index| %>
                <div class="col-lg-6 col-sm-6">
                  <div class="row border_bottom">
                    <div class="col-lg-12 col-sm-12 text-center both_border fill <%= index.zero? ? 'border-right' : '' %>">
                      <strong class="text-uppercase"><%= section %></strong>
                    </div>
                    <div class="col-lg-3 col-sm-3 border_bottom">
                      name:
                    </div>
                    <div class="col-lg-9 col-sm-9 border_bottom <%= index.zero? ? 'border-right' : '' %>">
                      <%= @invoice.client.name %>
                    </div>
                    <div class="col-lg-3 col-sm-3 border_bottom">
                      address:
                    </div>
                    <div class="col-lg-9 col-sm-9 border_bottom <%= index.zero? ? 'border-right' : '' %>">
                      <%= @invoice.client.address %>
                    </div>
                    <div class="col-lg-3 col-sm-3 border_bottom">
                      gstin:
                    </div>
                    <div class="col-lg-9 col-sm-9 border_bottom <%= index.zero? ? 'border-right' : '' %>">
                      <%= @invoice.client.gstno %>
                    </div>
                    <div class="col-lg-3 col-sm-3">
                      STATE :
                    </div>
                    <div class="col-lg-5 col-sm-4 border-right">
                      <%= @invoice.client.state %>
                    </div>
                    <div class="col-lg-2 col-sm-3">
                      CODE :
                    </div>
                    <div class="col-lg-2 col-sm-2 <%= index.zero? ? 'border-right' : '' %>">
                      <%= @invoice.client.code %>
                    </div>
                  </div>
                </div>
            <% end %>
          </div>

          <div class="row text-capitalize text-center mt-3 both_border" style="word-wrap: break-word">
            <div class="col-lg-12 col-sm-12 fill">
              <%= invoice_heading_row(@invoice) %>
            </div>
          </div>

          <% @invoice.invoice_items.each_with_index do |invoice_item, index| %>
              <div class="row light_border_bottom">
                <div class="col-lg-12 col-sm-12 text-capitalize text-center">
                    <%= invoice_content_row(@invoice, invoice_item, index) %>
                  </div>
              </div>
          <% end %>

          <% if @invoice.is_interstate?%>
          <%= render partial: 'interstate_bottom_section'%>
          <%else%>
              <%= render partial: 'intrastate_bottom_section'%>
          <%end%>
        </div>
      </div>
        <div class="page-break"></div>
  <% end %>
  <a href="javascript:void(0)" rel="print">Print</a>
  <%= link_to 'Edit', edit_invoice_path(@invoice) %>
  <%= link_to 'Back', invoices_path %>
</div>