config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :invoices
  resources :clients do
    resources :invoices
  end
  resources :companies do
    resources :invoices
  end

  root to: "companies#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :invoices, inverse_of: :client, dependent: :destroy
  validates :name, :address, presence: true, length: {minimum: 5}
  validates :code, presence: true, length: {minimum: 2}
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET companys/1/clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_path, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :address, :gstno, :state, :code)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
    <div class="row">
      <div class="col-md-6 mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control #{validation_class(client, :name)}", id: :client_name %>
        <% if (error_message_present_for?(client, :name)) %>
            <div class="invalid-feedback">
              <%== error_messages(client, :name) %>
            </div>
        <% end %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :address %>
        <%= form.text_field :address, class: "form-control #{validation_class(client, :address)}", id: :client_address %>
        <% if (error_message_present_for?(client, :address)) %>
            <div class="invalid-feedback">
              <%== error_messages(client, :address) %>
            </div>
        <% end %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :state %>
        <%= form.text_field :state, class: "form-control #{validation_class(client, :state)}", id: :client_state %>
        <% if (error_message_present_for?(client, :state)) %>
            <div class="invalid-feedback">
              <%== error_messages(client, :state) %>
            </div>
        <% end %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :gstno %>
        <%= form.text_field :gstno, class: "form-control #{validation_class(client, :gstno)}", id: :client_gstno %>
        <% if (error_message_present_for?(client, :gstno)) %>
            <div class="invalid-feedback">
              <%== error_messages(client, :gstno) %>
            </div>
        <% end %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :code %>
        <%= form.text_field :code, class: "form-control #{validation_class(client, :code)}", id: :client_code %>
        <% if (error_message_present_for?(client, :code)) %>
            <div class="invalid-feedback">
              <%== error_messages(client, :code) %>
            </div>
        <% end %>
      </div>
    </div>

    <%= form.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/clients/edit.html.erb
<div class="container mt-5">
  <section>
    <h1>Editing Client</h1>
  </section>

  <%= render 'form', client: @client %>

  <%= link_to 'Show', @client %> |
  <%= link_to 'Back', clients_path %>
</div>

app/views/clients/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Clients</h1>

    <p class="lead text-muted">List of all clients under PRABHAT companies</p>

    <p>
      <%= link_to "Add Client", new_client_path, class: 'btn btn-primary' %>
    </p>
  </div>
</section>

<div class="album text-muted">
  <div class="container">

    <div class="row">
      <% @clients.each do |client| %>
          <% bck_clr_1 = "#%06x" % (rand * 0xffffff) %>
          <% bck_clr_2 = "#%06x" % (rand * 0xffffff) %>
          <div class="card">

            <div class="table" table style="background: <%= bck_clr_1%>;
                    background: -webkit-linear-gradient(left, <%=bck_clr_1%> , <%=bck_clr_2%>);
                    background: -o-linear-gradient(right, <%=bck_clr_1%> , <%=bck_clr_2%>);
                    background: -moz-linear-gradient(right, <%=bck_clr_1%> , <%=bck_clr_2%>);
                    background: linear-gradient(to right, <%=bck_clr_1%> , <%=bck_clr_2%>);">
              <div class="table-row">
                <div class="table-cell">
                  <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link" id="dropdown<%= client.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= fa_icon "list" %></a>

                      <div class="dropdown-menu" aria-labelledby="dropdown<%= client.id %>">
                        <%= link_to "Create invoice", new_client_invoice_path(client), class: 'dropdown-item' %>
                        <%= link_to "Invoices", client_invoices_path(client), class: 'dropdown-item' %>
                        <%= link_to "Edit", edit_client_path(client), class: 'dropdown-item' %>
                        <%= link_to "Delete", client, method: :delete, data: {confirm: "Are you sure to delete \"#{client.name}\"?"}, class: 'dropdown-item' %>
                      </div>
                    </li>
                  </ul>
                </div>

                <div class=" table-cell align-middle ">
                  <%= link_to client, class: 'main-section' do %>
                      <div class="text-uppercase text-center"><%= client.name %></div>
                      <address>
                        <small><%= client.address %><br/> <%= client.state %><br/>
                          GST: <strong class="text-uppercase"><%= client.gstno%></strong></small>
                      </address>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<div class="container mt-5">
  <section>
    <h1>Add New Client</h1>
  </section>
  <%= render 'form', client: @client %>

  <%= link_to 'Back', clients_path %>
</div>

app/views/clients/show.html.erb
<div class="container mt-5">

  <p>
    <strong>Name:</strong>
    <%= @client.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @client.address %>
  </p>

  <p>
    <strong>Gstno:</strong>
    <%= @client.gstno %>
  </p>

  <p>
    <strong>State:</strong>
    <%= @client.state %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= @client.code %>
  </p>

  <%= link_to 'Edit', edit_client_path(@client) %> |
  <%= link_to 'Back', clients_path %>
</div>