config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :invoices
  resources :clients do
    resources :invoices
  end
  resources :companies do
    resources :invoices
  end

  root to: "companies#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :invoices, inverse_of: :company, dependent: :destroy

  validates :name, :address, :contact, :gstno, presence: true, length: {minimum: 5}
  validates :state, :code, presence: true, length: {minimum: 2}
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :address, :contact, :gstno, :state, :code, :account_no, :ifsc_code)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
  def validation_class(object, key)
    return unless object.errors.any?
    object.errors.include?(key) ? 'is-invalid' : 'is-valid'
  end

  def error_message_present_for?(object, key)
    object.errors.include?(key)
  end

  def error_messages(object, key)
    object.errors.full_messages_for(key).join('<br/>')
  end

  def active_tab_class(active_for)
    controller_name == active_for ? 'active' : ''
  end

  def invoice_heading_row(invoice)
    content_tag(:div, class: 'row no-gutters') do
      columns = if invoice.is_interstate?
                  {'S.no' => {'class' => 'col-lg-1 col-sm-1 border-right'},
                   'Product Description' => {'class' => 'col-lg-4 col-sm-4 border-right'},
                   'HSN code' => {'class' => 'col-lg-1 col-sm-1 border-right'},
                   'Taxable Value' => {'class' => 'col-lg-2 col-sm-2 border-right'},
                   'IGST' => {'class' => 'col-lg-2 col-sm-2 text-center border-right ',
                              'sub_columns' => {'rate' => {'class' => 'col-lg-6 col-sm-6 border-right border_top'},
                                                'amount' => {'class' => 'col-lg-6 col-sm-6 border_top'}
                              }},
                   'Total' => {'class' => 'col-lg-2 col-sm-2'}
                  }
                else
                  {'column1' => {'col-split' => true, 'class' => 'col-lg-2 col-sm-2 border-right',
                                 'multi_columns' => {'S.no' => {'class' => 'col-lg-3 col-sm-4 border-right'},
                                                     'Product Description' => {'class' => 'col-lg-9 col-sm-8'}
                                 }},
                   'column2' => {'col-split' => true, 'class' => 'col-lg-5 col-sm-5 border-right',
                                 'multi_columns' => {'HSN code' => {'class' => 'col-lg-2 col-sm-2 border-right'},
                                                     'UDM' => {'class' => 'col-lg-1 col-sm-1 border-right'},
                                                     'qty' => {'class' => 'col-lg-1 col-sm-1 border-right'},
                                                     'rate' => {'class' => 'col-lg-2 col-sm-2 border-right'},
                                                     'amount' => {'class' => 'col-lg-2 col-sm-2 border-right'},
                                                     'discount' => {'class' => 'col-lg-2 col-sm-2 border-right'},
                                                     'Taxable Value' => {'class' => 'col-lg-2 col-sm-2'},
                                 }},
                   'CGST' => {'class' => 'col-lg-2 col-sm-2 text-center border-right ',
                              'sub_columns' => {'rate' => {'class' => 'col-lg-6 col-sm-6 border-right border_top'},
                                                'amount' => {'class' => 'col-lg-6 col-sm-6 border_top'}
                              }},
                   'SGST' => {'class' => 'col-lg-2 col-sm-2 text-center border-right ',
                              'sub_columns' => {'rate' => {'class' => 'col-lg-6 col-sm-6 border-right border_top'},
                                                'amount' => {'class' => 'col-lg-6 col-sm-6 border_top'}
                              }},
                   'Total' => {'class' => 'col-lg-1 col-sm-1'}
                  }
                end
      columns.each_pair do |column_name, detail|
        concat(content_tag(:div, class: detail['class']) do
                 if (detail['col-split'])
                   concat(content_tag(:div, class: 'row no-gutters height-100') do
                            detail['multi_columns'].each_pair do |sub_coumn, sub_column_detail|
                              concat(content_tag(:div, class: sub_column_detail['class']) do
                                       sub_coumn
                                     end)
                            end
                          end)
                 elsif (detail['sub_columns'])
                   concat(column_name)
                   concat(content_tag(:div, class: 'row no-gutters') do
                            detail['sub_columns'].each_pair do |sub_coumn, sub_column_detail|
                              concat(content_tag(:div, class: sub_column_detail['class']) do
                                       sub_coumn
                                     end)
                            end
                          end)
                 else
                   column_name
                 end
               end)
      end
    end
  end

  def invoice_content_row(invoice, invoice_item, index)
    content_tag(:div, class: 'row no-gutters') do
      if invoice.is_interstate?
        concat(content_tag(:div, class: 'col-lg-1 col-sm-1 light_border_right') do
                 (index + 1).to_s
               end)
        concat(content_tag(:div, class: 'col-lg-4 col-sm-4 light_border_right') do
                 invoice_item.description
               end)
        concat(content_tag(:div, class: 'col-lg-1 col-sm-1 light_border_right') do
                 invoice_item.hsn_code
               end)
        concat(content_tag(:div, class: 'col-lg-2 col-sm-2 light_border_right') do
                 invoice_item.amount.to_s
               end)
        concat(content_tag(:div, class: 'col-lg-1 col-sm-1 light_border_right') do
                 invoice_item.display_gst_rate.to_s
               end)
        concat(content_tag(:div, class: 'col-lg-1 col-sm-1 light_border_right') do
                 invoice_item.gst_tax.to_s
               end)
        concat(content_tag(:div, class: 'col-lg-2 col-sm-2') do
                 invoice_item.total_amount.to_s
               end)
      else
        concat(content_tag(:div, class: 'col-lg-2 col-sm-2') do
           concat(content_tag(:div, class: 'row height-100 no-gutters') do

              concat(content_tag(:div, class: 'col-lg-3 col-sm-4 light_border_right') do
                       (index + 1).to_s
                     end)
              concat(content_tag(:div, class: 'col-lg-9 col-sm-8 light_border_right') do
                      invoice_item.description
                     end)
           end)
        end)

        concat(content_tag(:div, class: 'col-lg-5 col-sm-5') do
                 concat(content_tag(:div, class: 'row height-100 no-gutters') do

                          concat(content_tag(:div, class: 'col-lg-2 col-sm-2 light_border_right') do
                                   invoice_item.hsn_code
                                 end)
                          concat(content_tag(:div, class: 'col-lg-1 col-sm-1 light_border_right') do
                                   invoice_item.udm
                                 end)
                          concat(content_tag(:div, class: 'col-lg-1 col-sm-1 light_border_right') do
                                   invoice_item.quantity.to_s
                                 end)
                          concat(content_tag(:div, class: 'col-lg-2 col-sm-2 light_border_right') do
                                   invoice_item.rate.to_s
                                 end)
                          concat(content_tag(:div, class: 'col-lg-2 col-sm-2 light_border_right') do
                                   (invoice_item.rate * invoice_item.quantity).to_s
                                 end)
                          concat(content_tag(:div, class: 'col-lg-2 col-sm-2 light_border_right') do
                                   invoice_item.discount.to_s
                                 end)
                          concat(content_tag(:div, class: 'col-lg-2 col-sm-2 light_border_right') do
                                   invoice_item.amount.to_s
                                 end)
                        end)
               end)

        concat(content_tag(:div, class: 'col-lg-2 col-sm-2') do
                 concat(content_tag(:div, class: 'row height-100 no-gutters') do

                          concat(content_tag(:div, class: 'col-lg-6 col-sm-6 light_border_right') do
                                   invoice_item.display_gst_rate.to_s
                                 end)
                          concat(content_tag(:div, class: 'col-lg-6 col-sm-6 light_border_right') do
                                   invoice_item.gst_tax.to_s
                                 end)
                        end)
               end)

        concat(content_tag(:div, class: 'col-lg-2 col-sm-2') do
                 concat(content_tag(:div, class: 'row height-100 no-gutters') do

                          concat(content_tag(:div, class: 'col-lg-6 col-sm-6 light_border_right') do
                                   invoice_item.display_gst_rate.to_s
                                 end)
                          concat(content_tag(:div, class: 'col-lg-6 col-sm-6 light_border_right') do
                                   invoice_item.gst_tax.to_s
                                 end)
                        end)
               end)

        concat(content_tag(:div, class: 'col-lg-1 col-sm-1') do
                 invoice_item.total_amount.to_s
               end)
      end
    end

  end

end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
    <div class="row">
      <div class="col-md-6 mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control #{validation_class(company, :name)}", id: :company_name %>
        <% if (error_message_present_for?(company, :name)) %>
            <div class="invalid-feedback">
              <%== error_messages(company, :name) %>
            </div>
        <% end %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :address %>
        <%= form.text_field :address, class: "form-control #{validation_class(company, :address)}", id: :company_address %>
        <% if (error_message_present_for?(company, :address)) %>
            <div class="invalid-feedback">
              <%== error_messages(company, :address) %>
            </div>
        <% end %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :contact %>
        <%= form.text_field :contact, class: "form-control #{validation_class(company, :contact)}", id: :company_contact %>
        <% if (error_message_present_for?(company, :contact)) %>
            <div class="invalid-feedback">
              <%== error_messages(company, :contact) %>
            </div>
        <% end %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :gstno %>
        <%= form.text_field :gstno, class: "form-control #{validation_class(company, :gstno)}", id: :company_gstno %>
        <% if (error_message_present_for?(company, :gstno)) %>
            <div class="invalid-feedback">
              <%== error_messages(company, :gstno) %>
            </div>
        <% end %>
      </div>
      <div class="col-md-6 mb-3">
        <%= form.label :state %>
        <%= form.text_field :state, class: "form-control #{validation_class(company, :state)}", id: :company_state %>
        <% if (error_message_present_for?(company, :state)) %>
            <div class="invalid-feedback">
              <%== error_messages(company, :state) %>
            </div>
        <% end %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :code %>
        <%= form.text_field :code, class: "form-control #{validation_class(company, :code)}", id: :company_code %>
        <% if (error_message_present_for?(company, :code)) %>
            <div class="invalid-feedback">
              <%== error_messages(company, :code) %>
            </div>
        <% end %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :account_no %>
        <%= form.text_field :account_no, class: "form-control #{validation_class(company, :account_no)}", id: :company_account_no %>
        <% if (error_message_present_for?(company, :account_no)) %>
            <div class="invalid-feedback">
              <%== error_messages(company, :account_no) %>
            </div>
        <% end %>
      </div>

      <div class="col-md-6 mb-3">
        <%= form.label :ifsc_code %>
        <%= form.text_field :ifsc_code, class: "form-control #{validation_class(company, :ifsc_code)}", id: :company_ifsc_code %>
        <% if (error_message_present_for?(company, :ifsc_code)) %>
            <div class="invalid-feedback">
              <%== error_messages(company, :ifsc_code) %>
            </div>
        <% end %>
      </div>
    </div>

    <%= form.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/companies/edit.html.erb
<div class="container mt-5">
  <section>
    <h1>Editing Company</h1>
  </section>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>
</div>

app/views/companies/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Companies</h1>

    <p class="lead text-muted">List of all companies under PRABHAT TRAVELS</p>

    <p>
      <%= link_to "Add Company", new_company_path, class: 'btn btn-primary' %>
    </p>
  </div>
</section>

<div class="album text-muted">
  <div class="container">

    <div class="row">
      <% @companies.each do |company| %>
          <% bck_clr_1 = "#%06x" % (rand * 0xffffff) %>
          <% bck_clr_2 = "#%06x" % (rand * 0xffffff) %>
          <div class="card">

            <div class="table" table style="background: <%= bck_clr_1%>;
                    background: -webkit-linear-gradient(left, <%=bck_clr_1%> , <%=bck_clr_2%>);
                    background: -o-linear-gradient(right, <%=bck_clr_1%> , <%=bck_clr_2%>);
                    background: -moz-linear-gradient(right, <%=bck_clr_1%> , <%=bck_clr_2%>);
                    background: linear-gradient(to right, <%=bck_clr_1%> , <%=bck_clr_2%>);">
              <div class="table-row">
                <div class="table-cell">
                  <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                      <a class="nav-link" id="dropdown<%= company.id %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= fa_icon "list" %></a>

                      <div class="dropdown-menu" aria-labelledby="dropdown<%= company.id %>">
                        <%= link_to "Create invoice", new_company_invoice_path(company), class: 'dropdown-item' %>
                        <%= link_to "Invoices", company_invoices_path(company), class: 'dropdown-item' %>
                        <%= link_to "Edit", edit_company_path(company), class: 'dropdown-item' %>
                        <%= link_to "Delete", company, method: :delete, data: {confirm: "Are you sure to delete \"#{company.name}\"?"}, class: 'dropdown-item' %>
                      </div>
                    </li>
                  </ul>
                </div>

                <div class=" table-cell align-middle ">
                  <%= link_to company, class: 'main-section' do %>
                      <div class="text-uppercase text-center"><%= company.name %></div>
                      <address>
                        <small><%= company.address %><br/> <%= company.contact %><br/>
                        GST: <span class='text-uppercase'><%= company.gstno%></span></small>
                      </address>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<div class="container mt-5">
  <section>
    <h1>Add New Company</h1>
  </section>
<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>
</div>

app/views/companies/show.html.erb
<div class="container mt-5">

  <p>
    <strong>Name:</strong>
    <%= @company.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @company.address %>
  </p>

  <p>
    <strong>Contact:</strong>
    <%= @company.contact %>
  </p>

  <p>
    <strong>Gstno:</strong>
    <span class="text-uppercase"> <%= @company.gstno %></span>
  </p>

  <p>
    <strong>State:</strong>
    <%= @company.state %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= @company.code %>
  </p>

  <p>
    <strong>Account no:</strong>
    <%= @company.account_no %>
  </p>

  <p>
    <strong>ifsc Code:</strong>
    <%= @company.ifsc_code %>
  </p>

  <%= link_to 'Edit', edit_company_path(@company) %> |
  <%= link_to 'Back', companies_path %>
</div>